import {
  Absorption,
  Artifact,
  BonusType,
  Category,
  Class,
  DamageType,
  Realm,
  Resistance,
  ShieldSize,
  Skill,
  Slot,
  Stat,
  Tradeskill,
} from './types'

export interface IImbueValues {
  [k: string]: [number]
}

export const imbueValues: IImbueValues = {
  [BonusType.Stats]: [2, 5, 8, 11, 14, 17, 20, 23, 26, 29],
  [BonusType.Skills]: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  [BonusType.Hit_Points]: [4, 12, 20, 28, 36, 44, 52, 60, 68, 76],
  [BonusType.Resistance]: [1, 2, 3, 5, 7, 9, 11, 13, 15, 17],
}

// FROM ITEM DB

export const absorption = {
  [Absorption.Cloth]: 'Cloth',
  [Absorption.Leather]: 'Leather',
  [Absorption.Studded]: 'Studded',
  [Absorption.Chain]: 'Chain',
  [Absorption.Plate]: 'Plate',
}

export const artifact = {
  [Artifact.Arcane_Siphon]: 'Arcane Siphon',
  [Artifact.Conversion]: 'Conversion',
  [Artifact.Radiant_Aura]: 'Radiant Aura',
  [Artifact.XP_Bonus]: 'XP Bonus',
  [Artifact.Gold_Bonus]: 'Gold Bonus',
  [Artifact.Realm_Point_Bonus]: 'Realm Point Bonus',
  [Artifact.Bounty_Point_Bonus]: 'Bounty Point Bonus',
}

export const bonusType = {
  [BonusType.Stats]: 'Stats',
  [BonusType.Skills]: 'Skills',
  [BonusType.Hit_Points]: 'Hit Points',
  [BonusType.Resistance]: 'Resistance',
  [BonusType.Focus]: 'Focus',
  [BonusType.Toa_Melee_Damage]: 'Toa Melee Damage',
  [BonusType.Toa_Magic_Damage]: 'Toa Magic Damage',
  [BonusType.Toa_Style_Damage]: 'Toa Style Damage',
  [BonusType.Toa_Archery_Range]: 'Toa Archery Range',
  [BonusType.Toa_Spell_Range]: 'Toa Spell Range',
  [BonusType.Toa_Spell_Duration]: 'Toa Spell Duration',
  [BonusType.Toa_Buff_Bonus]: 'Toa Buff Bonus',
  [BonusType.Toa_Debuff_Bonus]: 'Toa Debuff Bonus',
  [BonusType.Toa_Heal_Bonus]: 'Toa Heal Bonus',
  [BonusType.Toa_Fatigue]: 'Toa Fatigue',
  [BonusType.Toa_Melee_Speed]: 'Toa Melee Speed',
  [BonusType.Toa_Archery_Speed]: 'Toa Archery Speed',
  [BonusType.Toa_Cast_Speed]: 'Toa Cast Speed',
  [BonusType.Armor_Factor]: 'Armor Factor (AF)',
  [BonusType.Crafting_Min_Quality]: 'Crafting Min Quality',
  [BonusType.Crafting_Quality]: 'Crafting Quality',
  [BonusType.Crafting_Speed]: 'Crafting Speed',
  [BonusType.Crafting_Skill_Gain]: 'Crafting Skill Gain',
  [BonusType.Toa_Archery_Damage]: 'Toa Archery Damage',
  [BonusType.Toa_Overcap]: 'Toa Overcap',
  [BonusType.Toa_Hit_Points_Cap]: 'Toa Hit Points Cap',
  [BonusType.Toa_Power_Pool_Cap]: 'Toa Power Pool Cap',
  [BonusType.Toa_Fatigue_Cap]: 'Toa Fatigue Cap',
  [BonusType.Toa_Resistance_Piece]: 'Toa Resistance Piece',
  [BonusType.Toa_Power_Pool]: 'Toa Power Pool',
  [BonusType.Toa_Artifact]:
    'Toa Artifact (Arcane Siphon / Conversion / Radiant Aura / Money / Exp / RPs / BPs)',
  [BonusType.Spell_Power_Cost_Reduction_PvE]:
    'Spell Power Cost Reduction (PvE)',
  [BonusType.Concentration]: 'Concentration',
  [BonusType.Health_Regeneration]: 'Health Regeneration',
  [BonusType.Mana_Regeneration]: 'Mana Regeneration',
  [BonusType.Piece_Ablative_PvE]: 'Piece Ablative (PvE)',
  [BonusType.Death_Experience_Loss_Reduction]:
    'Death Experience Loss Reduction',
  [BonusType.Negative_Effect_Duration_Reduction_PvE]:
    'Negative Effect Duration Reduction (PvE)',
  [BonusType.Style_Cost_Reduction_PvE]: 'Style Cost Reduction (PvE)',
  [BonusType.To_Hit_Bonus_PvE]: 'To Hit Bonus (PvE)',
  [BonusType.Defensive_Bonus_PvE]: 'Defensive Bonus (PvE)',
  [BonusType.Bladeturn_Reinforcement]: 'Bladeturn Reinforcement',
  [BonusType.Parry_PvE]: 'Parry (PvE)',
  [BonusType.Block_PvE]: 'Block (PvE)',
  [BonusType.Evade_PvE]: 'Evade (PvE)',
  [BonusType.Reactionary_Style_Damage_Bonus_PvE]:
    'Reactionary Style Damage Bonus (PvE)',
  [BonusType.Mythical_Encumbrance]: 'Mythical Encumbrance',
  [BonusType.Mythical_Resistance_Cap]: 'Mythical Resistance Cap',
  [BonusType.Mythical_Siege_Speed]: 'Mythical Siege Speed',
  [BonusType.Mythical_Parry]: 'Mythical Parry',
  [BonusType.Mythical_Evade]: 'Mythical Evade',
  [BonusType.Mythical_Block]: 'Mythical Block',
  [BonusType.Mythical_Coin]: 'Mythical Coin',
  [BonusType.Mythical_Cap_Increase]: 'Mythical Cap Increase',
  [BonusType.Mythical_Crowd_Control_Duration_Decrease]:
    'Mythical Crowd Control Duration Decrease',
  [BonusType.Mythical_Essence_Resist]: 'Mythical Essence Resist',
  [BonusType.Mythical_Resist_and_Cap]: 'Mythical Resist and Cap',
  [BonusType.Mythical_Siege_Damage_Ablative]: 'Mythical Siege Damage Ablative',
  [BonusType.Mythical_DPS]: 'Mythical DPS',
  [BonusType.Mythical_Realm_Points]: 'Mythical Realm Points',
  [BonusType.Mythical_Spell_Focus]: 'Mythical Spell Focus',
  [BonusType.Mythical_Resurrection_Sickness_Reduction]:
    'Mythical Resurrection Sickness Reduction',
  [BonusType.Mythical_Stat_and_Cap_Increase]: 'Mythical Stat and Cap Increase',
  [BonusType.Mythical_Health_Regen]: 'Mythical Health Regen',
  [BonusType.Mythical_Power_Regen]: 'Mythical Power Regen',
  [BonusType.Mythical_Endurance_Regen]: 'Mythical Endurance Regen',
  [BonusType.Mythical_Physical_Defense]: 'Mythical Physical Defense',
}

export const categories = {
  [Category.Weapon]: 'Weapon',
  [Category.Armor]: 'Armor',
  [Category.Shield]: 'Shield',
  [Category.Instrument]: 'Instrument',
  [Category.Jewelry]: 'Jewelry',
  [Category.Mount]: 'Mount',
  [Category.Consumable]: 'Consumable',
  [Category.Other]: 'Other',
}

export const damageType = {
  [DamageType.Crush]: 'Crush',
  [DamageType.Slash]: 'Slash',
  [DamageType.Thrust]: 'Thrust',
  [DamageType.Siege]: 'Siege',
  [DamageType.Spirit]: 'Spirit',
}

export const realm = {
  [Realm.All]: 'All',
  [Realm.Albion]: 'Albion',
  [Realm.Midgard]: 'Midgard',
  [Realm.Hibernia]: 'Hibernia',
}

export const resists = {
  [Resistance.Stats]: 'Stats',
  [Resistance.Crush_0]: 'Crush',
  [Resistance.Slash_0]: 'Slash',
  [Resistance.Thrust_0]: 'Thrust',
  [Resistance.Siege]: 'Siege',
  [Resistance.Heat_0]: 'Heat',
  [Resistance.Spirit_0]: 'Spirit',
  [Resistance.Cold_0]: 'Cold',
  [Resistance.Matter_0]: 'Matter',
  [Resistance.Heat_1]: 'Heat',
  [Resistance.Matter_1]: 'Matter',
  [Resistance.Body_0]: 'Body',
  [Resistance.Spirit_1]: 'Spirit',
  [Resistance.Energy_0]: 'Energy',
  [Resistance.Cold_1]: 'Cold',
  [Resistance.Energy_1]: 'Energy',
  [Resistance.Essence_0]: 'Essence',
  [Resistance.Energy_2]: 'Energy',
  [Resistance.Cold_2]: 'Cold',
  [Resistance.Body_2]: 'Body',
  [Resistance.Body_3]: 'Body',
  [Resistance.Body_4]: 'Body',
}

export const skills = {
  [Skill.Slash]: 'Slash',
  [Skill.Thrust]: 'Thrust',
  [Skill.Bow]: 'Bow',
  [Skill.Parry]: 'Parry',
  [Skill.Sword]: 'Sword',
  [Skill.Hammer]: 'Hammer',
  [Skill.Axe]: 'Axe',
  [Skill.LeftAxe]: 'LeftAxe',
  [Skill.Stealth]: 'Stealth',
  [Skill.Spear]: 'Spear',
  [Skill.Mending]: 'Mending',
  [Skill.Augmentation]: 'Augmentation',
  [Skill.Crush]: 'Crush',
  [Skill.Pacification]: 'Pacification',
  [Skill.Cave_Magic]: 'Cave Magic',
  [Skill.Darkness]: 'Darkness',
  [Skill.Suppression]: 'Suppression',
  [Skill.Runecarving]: 'Runecarving',
  [Skill.Shield]: 'Shield',
  [Skill.Thrown]: 'Thrown',
  [Skill.Flexible]: 'Flexible',
  [Skill.Staff]: 'Staff',
  [Skill.Summoning]: 'Summoning',
  [Skill.Stormcalling]: 'Stormcalling',
  [Skill.Beastcraft]: 'Beastcraft',
  [Skill.Polearm]: 'Polearm',
  [Skill.Two_Handed]: 'Two Handed',
  [Skill.Fire_Magic]: 'Fire Magic',
  [Skill.Wind_Magic]: 'Wind Magic',
  [Skill.Cold_Magic]: 'Cold Magic',
  [Skill.Earth_Magic]: 'Earth Magic',
  [Skill.Light_Magic]: 'Light Magic',
  [Skill.Matter_Magic]: 'Matter Magic',
  [Skill.Body_Magic]: 'Body Magic',
  [Skill.Spirit_Magic]: 'Spirit Magic',
  [Skill.Mind_Magic]: 'Mind Magic',
  [Skill.Void_Magic]: 'Void Magic',
  [Skill.Mana_Magic]: 'Mana Magic',
  [Skill.Dual_Wield]: 'Dual Wield',
  [Skill.Composite_Bow]: 'Composite Bow',
  [Skill.Envenom_0]: 'Envenom',
  [Skill.Battlesongs]: 'Battlesongs',
  [Skill.Enhancements]: 'Enhancements',
  [Skill.Enchantments]: 'Enchantments',
  [Skill.Illusions]: 'Illusions',
  [Skill.Rejuvenation]: 'Rejuvenation',
  [Skill.Smiting]: 'Smiting',
  [Skill.Longbow]: 'Longbow',
  [Skill.Crossbow]: 'Crossbow',
  [Skill.Flute]: 'Flute',
  [Skill.Chants]: 'Chants',
  [Skill.Instruments]: 'Instruments',
  [Skill.Blades]: 'Blades',
  [Skill.Blunt]: 'Blunt',
  [Skill.Piercing]: 'Piercing',
  [Skill.Large_Weaponry]: 'Large Weaponry',
  [Skill.Mentalism]: 'Mentalism',
  [Skill.Regrowth]: 'Regrowth',
  [Skill.Nurture]: 'Nurture',
  [Skill.Nature_Affinity]: 'Nature Affinity',
  [Skill.Music]: 'Music',
  [Skill.Celtic_Dual]: 'Celtic Dual',
  [Skill.Celtic_Spear]: 'Celtic Spear',
  [Skill.Recurve_Bow]: 'Recurve Bow',
  [Skill.Valor]: 'Valor',
  [Skill.Envenom_1]: 'Envenom',
  [Skill.Critical_Strike]: 'Critical Strike',
  [Skill.Nightshade]: 'Nightshade',
  [Skill.Deathsight]: 'Deathsight',
  [Skill.Painworking]: 'Painworking',
  [Skill.Death_Servant]: 'Death Servant',
  [Skill.Soulrending]: 'Soulrending',
  [Skill.Hand_to_Hand]: 'Hand to Hand',
  [Skill.Scythe]: 'Scythe',
  [Skill.Bone_Army]: 'Bone Army',
  [Skill.Arboreal_Path]: 'Arboreal Path',
  [Skill.Savagery]: 'Savagery',
  [Skill.Creeping_Path]: 'Creeping Path',
  [Skill.Verdant_Path]: 'Verdant Path',
  [Skill.Odins_Will]: "Odin's Will",
  [Skill.Spectral_Guard]: 'Spectral Guard',
  [Skill.Phantasmal_Wail]: 'Phantasmal Wail',
  [Skill.Ethereal_Shriek]: 'Ethereal Shriek',
  [Skill.Shadow_Mastery]: 'Shadow Mastery',
  [Skill.Vampiiric_Embrace]: 'Vampiiric Embrace',
  [Skill.Dementia]: 'Dementia',
  [Skill.Witchcraft]: 'Witchcraft',
  [Skill.Cursing]: 'Cursing',
  [Skill.Hexing]: 'Hexing',
  [Skill.Power_Strikes]: 'Power Strikes',
  [Skill.Magnetism]: 'Magnetism',
  [Skill.Aura_Manipulation]: 'Aura Manipulation',
  [Skill.Fist_Wraps]: 'Fist Wraps',
  [Skill.Mauler_Staff]: 'Mauler Staff',
  [Skill.All_Melee]: 'All Melee',
  [Skill.All_Duel]: 'All Duel',
  [Skill.All_Archery]: 'All Archery',
  [Skill.All_Casting]: 'All Casting',
  [Skill.All_Focus]: 'All Focus',
}

export const stats = {
  [Stat.Strength]: 'Strength',
  [Stat.Dexterity]: 'Dexterity',
  [Stat.Constitution]: 'Constitution',
  [Stat.Quickness]: 'Quickness',
  [Stat.Intelligence]: 'Intelligence',
  [Stat.Piety]: 'Piety',
  [Stat.Empathy]: 'Empathy',
  [Stat.Charisma]: 'Charisma',
  [Stat.Acuity]: 'Acuity',
}

export const shieldSize = {
  [ShieldSize.Small]: 'Small',
  [ShieldSize.Medium]: 'Medium',
  [ShieldSize.Large]: 'Large',
}

export const slot = {
  [Slot.Helm]: 'Helm',
  [Slot.Hands]: 'Hands',
  [Slot.Feet]: 'Feet',
  [Slot.Torso]: 'Torso',
  [Slot.Legs]: 'Legs',
  [Slot.Arms]: 'Arms',
}

export const tradeskills = {
  [Tradeskill.Weaponcraft]: 'Weaponcraft',
  [Tradeskill.Armorcraft]: 'Armorcraft',
  [Tradeskill.Siegecraft]: 'Siegecraft',
  [Tradeskill.Alchemy]: 'Alchemy',
  [Tradeskill.Tailoring]: 'Tailoring',
  [Tradeskill.Fletching]: 'Fletching',
  [Tradeskill.Spellcrafting]: 'Spellcrafting',
}

export const usableBy = {
  [Class.Paladin]: 'Paladin',
  [Class.Armsman]: 'Armsman',
  [Class.Scout]: 'Scout',
  [Class.Minstrel]: 'Minstrel',
  [Class.Theurgist]: 'Theurgist',
  [Class.Cleric]: 'Cleric',
  [Class.Wizard]: 'Wizard',
  [Class.Sorcerer]: 'Sorcerer',
  [Class.Infiltrator]: 'Infiltrator',
  [Class.Friar]: 'Friar',
  [Class.Mercenary]: 'Mercenary',
  [Class.Necromancer]: 'Necromancer',
  [Class.Cabalist]: 'Cabalist',
  [Class.Reaver]: 'Reaver',
  [Class.Thane]: 'Thane',
  [Class.Warrior]: 'Warrior',
  [Class.Shadowblade]: 'Shadowblade',
  [Class.Skald]: 'Skald',
  [Class.Hunter]: 'Hunter',
  [Class.Healer]: 'Healer',
  [Class.Spiritmaster]: 'Spiritmaster',
  [Class.Shaman]: 'Shaman',
  [Class.Runemaster]: 'Runemaster',
  [Class.Bonedancer]: 'Bonedancer',
  [Class.Berserker]: 'Berserker',
  [Class.Savage]: 'Savage',
  [Class.Heretic]: 'Heretic',
  [Class.Valkyrie]: 'Valkyrie',
  [Class.Bainshee]: 'Bainshee',
  [Class.Eldritch]: 'Eldritch',
  [Class.Enchanter]: 'Enchanter',
  [Class.Mentalist]: 'Mentalist',
  [Class.Blademaster]: 'Blademaster',
  [Class.Hero]: 'Hero',
  [Class.Champion]: 'Champion',
  [Class.Warden]: 'Warden',
  [Class.Druid]: 'Druid',
  [Class.Bard]: 'Bard',
  [Class.Nightshade]: 'Nightshade',
  [Class.Ranger]: 'Ranger',
  [Class.Animist]: 'Animist',
  [Class.Valewalker]: 'Valewalker',
  [Class.Vampiir]: 'Vampiir',
  [Class.Warlock]: 'Warlock',
  [Class.Mauler_Alb]: 'Mauler (Alb)',
  [Class.Mauler_Mid]: 'Mauler (Mid)',
  [Class.Mauler_Hib]: 'Mauler (Hib)',
}

export const magicType = {
  1: 'Offensive Proc',
  2: 'Reactive Proc',
  3: 'Worn',
  4: 'Worn',
  6: 'Charge',
}

export const position = {
  1: '/use1',
  2: '/use2',
}

export const spell = {
  431: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  488: 'The target is mesmerized and cannot take any actions.',
  490: 'Summons a divine spirit to attack the target.',
  497: 'Summons a tomte ruffian to attack the target',
  592: 'Does 22.0 Spirit damage to the target.',
  594: 'Does 39.0 Spirit damage to the target.',
  598: 'The target regains 15% power points.',
  635: 'Does 57.0 Spirit damage to the target.',
  637: 'The target regains 20% power points.',
  639: 'Does 75.0 Spirit damage to the target.',
  643: 'The target regains 25% power points.',
  1064: 'Does 92.0 Spirit damage to the target.',
  1183: 'The target regains 30% power points.',
  1197: 'Does 110.0 Spirit damage to the target.',
  1198: 'The target regains 35% power points.',
  1243: 'Does 127.0 Spirit damage to the target.',
  1244: 'The target regains 35% power points.',
  1264: 'Does 145.0 Spirit damage to the target.',
  1265: 'The target regains 35% power points.',
  1579: 'The target regains 50% power points.',
  1581: 'The target regains 130 hit points.',
  1582: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  1583: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 500 damage.',
  1584: 'Increases your dexterity by 50.',
  1586: 'Does 331.5 Heat damage to the target.',
  1587: '25% endurance is stolen from the target and given to the caster.',
  1588: "Reduces the target's absorption (ABS) by 20%%.",
  1589: "Target's attack speed reduced by 40% for 20 sec.",
  1590: 'Target moves 40% slower for 20 sec.',
  1591: 'The target regains 50% power points.',
  1592: 'You regenerate 4 extra power.',
  1593: "Decreases the target's resistances to Crush damage by 5%.",
  1594: "Decreases the target's resistances to Slash damage by 5%.",
  1595: "Decreases the target's resistances to Thrust damage by 5%.",
  1821: 'Does 204.3 Cold damage to the target.',
  1880: 'Does 72.0 Body damage to the target.',
  1899: 'Inflicts a wasting disease on the target that slows target by 15%, reduces its strength by 10 and inhibits healing by 50%.',
  1992: "Increases the target's resistance to Crush, Slash and Thrust damage by 10%.",
  1993: 'You regenerate 2 extra power.',
  1994: 'You regenerate 1 extra fatigue.',
  1995: 'Does 18.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  1996: 'Increases your attack speed by 5%.',
  2025: '2% Accuracy bonus granted to the player for landing all spells, melee, and ranged attacks. Duration: 30 seconds.',
  2026: "Target's armor becomes 2% less effective for 30 sec.",
  2027: "Target's strength and constitution are reduced by 15.",
  2028: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 90 damage.',
  2029: 'Does 27.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2030: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 125 damage.',
  2031: 'You regenerate 2 extra power.',
  2032: 'You regenerate 1 extra fatigue.',
  2033: 'Does 36.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2034: 'Increases your attack speed by 10%.',
  2035: '4% Accuracy bonus granted to the player for landing all spells, melee, and ranged attacks. Duration: 30 seconds.',
  2036: "Target's armor becomes 4% less effective for 30 sec.",
  2038: "Target's strength and constitution are reduced by 22.",
  2039: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 165 damage.',
  2040: 'Does 45.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2041: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 200 damage.',
  2042: 'You regenerate 2 extra power.',
  2043: 'You regenerate 1 extra fatigue.',
  2044: 'Does 55.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2045: 'Increases your attack speed by 15%.',
  2046: '6% Accuracy bonus granted to the player for landing all spells, melee, and ranged attacks. Duration: 30 seconds.',
  2047: "Target's armor becomes 6% less effective for 30 sec.",
  2048: "Target's strength and constitution are reduced by 29.",
  2049: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 240 damage.',
  2083: 'Does 64.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2084: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 275 damage.',
  2085: 'You regenerate 2 extra power.',
  2086: 'You regenerate 1 extra fatigue.',
  2087: 'Does 73.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2088: 'Increases your attack speed by 20%.',
  2089: '8% Accuracy bonus granted to the player for landing all spells, melee, and ranged attacks. Duration: 30 seconds.',
  2090: "Reduces the target's absorption (ABS) by 10%.",
  2091: "Target's strength and constitution are reduced by 43.",
  2092: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  2093: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  2094: 'You regenerate 2 extra power.',
  2095: 'You regenerate 1 extra fatigue.',
  2096: 'Increases your attack speed by 25%.',
  2097: '10% Accuracy bonus granted to the player for landing all spells, melee, and ranged attacks. Duration: 30 seconds.',
  2339: "Increases the target's resistance to Crush, Slash and Thrust damage by 20%.",
  2340: "Reduces the target's absorption (ABS) by 15%.",
  2341: 'You regenerate 5 extra power.',
  2849: "The target's armor and health are improved by 5% while within range of this aura.",
  3258: 'Summons an insect swarm to attack the target.',
  3359: 'Increases your combat speed by 18%.',
  3361: 'Heals the target for 10% health, power and fatigue.',
  3370: 'The target regains 50% power points.',
  3371: 'You gain a 15% bonus to armor and health.',
  3372: "Target's attack speed reduced by 31%.",
  3373: "Reduces the target's armor factor (AF) by 55 for 15 sec.",
  3374: "Reduces the target's absorption (ABS) by 15%.",
  3377: 'Increases your Slash by 10%.',
  3378: 'Increases your Thrust by 10%.',
  3379: 'Increases your Crush by 10%.',
  3380: 'Increases your Flexible by 10%.',
  3381: 'Increases your Staff by 10%.',
  3383: 'Increases your Sword by 10%.',
  3384: 'Increases your Axe by 10%.',
  3385: 'Increases your Hammer by 10%.',
  3386: 'Increases your Spear by 10%.',
  3387: 'Increases your Scythe by 10%.',
  3389: 'Increases your Blades by 10%.',
  3390: 'Increases your Blunt by 10%.',
  3403: 'Target gains a temporary health buffer that absorbs 50% of the magical damage dealt, up to a maximum of 500 damage.',
  3405: "Reduces the target's armor factor (AF) by 55 for 20 sec.",
  3406: '15% Accuracy bonus granted to the player for landing melee, magic and ranged attacks.\n\n Duration: 30 seconds',
  3407: 'You gain a 10% immunity to melee damage and a 50 bonus to all stats for 30 sec.',
  3408: 'Does 105.0 Heat damage to the target.',
  3409: 'Does 105.0 Cold damage to the target.',
  3410: 'Does 105.0 Body damage to the target.',
  3411: 'Increases your Dual Wield by 10%.',
  3412: 'Increases your Left Axe by 10%.',
  3413: 'Increases your Celtic Dual by 10%.',
  3419: "Reduces the target's absorption (ABS) by 10%.",
  3420: "Increases the target's cast speed by 65%.",
  3421: 'Target suffers a 10% penalty to their melee and ranged attacks.',
  3422: "Target's movement is reduced by 25% and their combat accuracy is reduced by 10% for 30 sec.This snare is not broken when the target is struck in battle.",
  3423: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  3424: 'Increases your attack speed by 25%.',
  3425: 'Inflicts a wasting disease on the target that slows target by 15%, reduces its strength by 15 and inhibits healing by 50%.',
  3427: 'Target gains a 50% chance to resist debuff spells for 20 sec.',
  3429: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 500 damage.',
  3430: 'Target suffers a penalty to every stat and a weakness to melee damage.\n\n Penalty to all stats: 35\n Vulnerability to melee: 5%\n Target: Targeted\n Range: 500\n Duration: 20s\n Casting time: instant\n Damage: Body',
  3431: 'Heals the target for 15% health, power and fatigue.',
  3432: 'Does 46.8 Heat damage to the target.',
  3440: 'Does 46.8 Cold damage to the target.',
  3445: 'Does 46.8 Body damage to the target.',
  3451: 'Blocks 10.0% damage and returns 10.0% to the caster as power.',
  3464: 'You gain a 5% bonus to armor and health.',
  3465: 'Cures both Disease and Poison from the user.',
  3473: 'Increases your melee absorption by 40.',
  3476: 'Bedazzles target, causing it to suffer a 35% chance to miscast and a 0% chance to fumble for 30 sec.',
  3477: 'Bedazzles target, causing it to suffer a undefined% chance to miscast and a 15% chance to fumble for 30 sec.',
  3478: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 500 damage.',
  3482: 'The target regains 10% hit points.',
  3483: "Increases the target's resistance to Crush, Slash and Thrust damage by 10%.",
  3484: "Target becomes 15% less effective at casting and resisting spells 15%. Reports target's primary specialization.",
  3485: 'You regenerate 5% health, endurance and power every 4.999 sec.',
  3590: 'You become immune to the next mesmerize spell cast on yourself.',
  3592: 'Absorbs 25% style damage.',
  3657: 'Triggers the following spell with a 15% chance when being attacked.',
  3680: 'The target is slowed by 60%.',
  3681: 'Heals target within view of the caster for 33% health.',
  3682: 'Brings the target back to life, restores 10% and 0% power and endurance and suffers no experience or constitution loss.',
  3684: 'The target regains 280 hit points.',
  3685: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 200 damage.',
  3686: 'Triggers the following spell with a 5% chance on own attacks.',
  3687: 'Heals the target for 18% health, power and fatigue.',
  3695: 'Increases your Axe by 10%.',
  3696: 'Increases your Sword by 10%.',
  3701: 'Does 41.0 Heat damage to the target.',
  3703: 'Does 59.0 Heat damage to the target.',
  3704: 'Does 68.0 Heat damage to the target.',
  3705: 'Does 77.0 Heat damage to the target.',
  3706: 'Does 86.0 Heat damage to the target.',
  3707: 'Does 95.0 Heat damage to the target.',
  3709: 'Does 50.0 Cold damage to the target.',
  3710: 'Does 59.0 Cold damage to the target.',
  3711: 'Does 68.0 Cold damage to the target.',
  3712: 'Does 77.0 Cold damage to the target.',
  3713: 'Does 86.0 Cold damage to the target.',
  3714: 'Does 95.0 Cold damage to the target.',
  3715: 'Does 41.0 Spirit damage to the target.',
  3716: 'Does 50.0 Spirit damage to the target.',
  3717: 'Does 59.0 Spirit damage to the target.',
  3718: 'Does 68.0 Spirit damage to the target.',
  3719: 'Does 77.0 Spirit damage to the target.',
  3720: 'Does 86.0 Spirit damage to the target.',
  3721: 'Does 95.0 Spirit damage to the target.',
  3723: 'Does 50.0 Energy damage to the target.',
  3724: 'Does 59.0 Energy damage to the target.',
  3725: 'Does 68.0 Energy damage to the target.',
  3726: 'Does 77.0 Energy damage to the target.',
  3727: 'Does 86.0 Energy damage to the target.',
  3728: 'Does 95.0 Energy damage to the target.',
  3731: 'Does 59.0 Energy damage to the target.',
  3733: 'Does 77.0 Energy damage to the target.',
  3734: 'Does 86.0 Energy damage to the target.',
  3735: 'Does 95.0 Energy damage to the target.',
  3736: 'Does 41.0 Heat damage to the target.',
  3738: 'Does 59.0 Heat damage to the target.',
  3739: 'Does 68.0 Heat damage to the target.',
  3740: 'Does 77.0 Heat damage to the target.',
  3741: 'Does 86.0 Heat damage to the target.',
  3742: 'Does 95.0 Heat damage to the target.',
  3745: 'Does 59.0 Cold damage to the target.',
  3746: 'Does 68.0 Cold damage to the target.',
  3747: 'Does 77.0 Cold damage to the target.',
  3748: 'Does 86.0 Cold damage to the target.',
  3749: 'Does 95.0 Cold damage to the target.',
  3751: 'Does 50.0 Cold damage to the target.',
  3753: 'Does 68.0 Cold damage to the target.',
  3754: 'Does 77.0 Cold damage to the target.',
  3755: 'Does 86.0 Cold damage to the target.',
  3756: 'Does 95.0 Cold damage to the target.',
  3769: 'Target takes 37 Heat damage every 4.999 seconds.',
  3770: 'Target takes 43 Heat damage every 4.999 seconds.',
  3771: 'Target takes 50 Heat damage every 4.999 seconds.',
  3772: 'Target takes 57 Heat damage every 4.999 seconds.',
  3773: 'Target takes 64 Heat damage every 4.999 seconds.',
  3774: 'Does 44.2 Heat damage to the target.',
  3775: 'Does 51.0 Heat damage to the target.',
  3776: 'Does 57.7 Heat damage to the target.',
  3777: 'Does 64.5 Heat damage to the target.',
  3778: 'Does 71.2 Heat damage to the target.',
  3779: 'The target deals 3.3 Heat damage to enemies that hit them with a melee attack.',
  3780: 'The target deals 3.8 Heat damage to enemies that hit them with a melee attack.',
  3781: 'The target deals 4.2 Heat damage to enemies that hit them with a melee attack.',
  3782: 'The target deals 4.7 Heat damage to enemies that hit them with a melee attack.',
  3783: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  3784: 'You regenerate 29 extra health.',
  3785: 'You regenerate 40 extra health.',
  3786: 'You regenerate 52 extra health.',
  3787: 'The target regains 120 hit points.',
  3788: 'The target regains 130 hit points.',
  3789: 'The target regains 180 hit points.',
  3791: 'You regain 20 endurance.',
  3792: 'You regain 40 endurance.',
  3793: 'You regain 60 endurance.',
  3795: 'The target regains 30 power points.',
  3796: 'The target regains 50 power points.',
  3804: 'The target deals 3.3 Body damage to enemies that hit them with a melee attack.',
  3805: 'The target deals 4.2 Body damage to enemies that hit them with a melee attack.',
  3807: 'Increases your combat speed by 11%.',
  3808: 'Increases your combat speed by 14%.',
  3809: 'Increases your combat speed by 17%.',
  3811: 'You regenerate 4 extra health.',
  3812: 'You regenerate 6 extra health.',
  3813: 'You regenerate 8 extra health.',
  3814: 'You regenerate 1 extra fatigue.',
  3816: 'You regenerate 3 extra fatigue.',
  3818: 'You regenerate 1 extra power.',
  3819: 'You regenerate 2 extra power.',
  3820: 'You regenerate 3 extra power.',
  3821: 'You regenerate 4 extra power.',
  3822: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 50 damage.',
  3823: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 100 damage.',
  3824: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  3825: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  3826: 'Target takes 64 Matter damage every 4.000 seconds.',
  3827: 'Target takes 64 Body damage every 4.000 seconds.',
  3828: 'Target takes 64 Energy damage every 4.000 seconds.',
  3829: 'Your melee attacks do additional 11.3 Matter damage.',
  3830: 'Your melee attacks do additional 11.3 Body damage.',
  3831: 'Your melee attacks do additional 11.3 Energy damage.',
  3832: 'The target takes 65.0 Body damage and the attacker is healed for 100% of the damage dealt.',
  3833: 'The target takes 65.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  3834: 'The target takes 65.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  3835: "Creates a 'bubble' that absorbs the damage of a single melee hit.",
  3838: 'Increases your combat speed by 20%.',
  3839: 'Increases your combat speed by 20%.',
  3840: 'Increases your combat speed by 20%.',
  3841: "Target's strength and constitution are reduced by 56.",
  3842: "Target's strength and constitution are reduced by 56.",
  3843: "Target's strength and constitution are reduced by 56.",
  3844: "Target's dexterity and quickness are reduced by 56.",
  3845: "Target's dexterity and quickness are reduced by 56.",
  3846: "Target's dexterity and quickness are reduced by 56.",
  3847: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  3848: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  3849: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  3850: 'Increases your armor factor (AF) by 75.',
  3851: 'Increases your armor factor (AF) by 75.',
  3852: 'Increases your armor factor (AF) by 75.',
  3853: "Target's strength and constitution are increased by 75.",
  3854: "Target's strength and constitution are increased by 75.",
  3855: "Target's strength and constitution are increased by 75.",
  3856: "Target's dexterity and quickness are increased by 75.",
  3857: "Target's dexterity and quickness are increased by 75.",
  3858: "Target's dexterity and quickness are increased by 75.",
  3859: 'Does 331.5 Heat damage to the target.',
  3860: 'Does 331.5 Cold damage to the target.',
  3861: 'Does 331.5 Spirit damage to the target.',
  3862: 'Does 331.5 Energy damage to the target.',
  3863: 'Does 331.5 Energy damage to the target.',
  3864: 'Does 331.5 Heat damage to the target.',
  3865: 'Does 331.5 Cold damage to the target.',
  3866: 'Does 331.5 Cold damage to the target.',
  3867: "Target's acuity are increased by 75.",
  3868: "Target's acuity are increased by 75.",
  3869: "Target's acuity are increased by 75.",
  3874: "Target's strength and constitution are increased by 30.",
  3875: "Target's dexterity and quickness are increased by 30.",
  3880: "Target's attack speed reduced by 20%.",
  3882: "Does 142.8 Body damage and decreases the target's resistances to Body by 10%.",
  3884: 'Increases your armor factor (AF) by 75.',
  3885: 'Increases your armor factor (AF) by 75.',
  3887: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  3888: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  4000: '',
  6910: 'Grants the target 5% additional spell damage and a 5% chance to penetrate magical resistances.',
  6911: 'Summons an elemental spirit to attack the target.',
  6916: "Creates an item in the caster's inventory.",
  6918: "Creates an item in the caster's inventory.",
  6919: "Creates an item in the caster's inventory.",
  6920: "Creates an item in the caster's inventory.",
  6921: "Creates an item in the caster's inventory.",
  6922: "Creates an item in the caster's inventory.",
  6923: 'The target regains 150 hit points.',
  6924: 'The target regains 250 hit points.',
  6925: 'All damage over time effects (such as poisons) are removed from you.',
  6926: 'All disease effects are removed from you.',
  6927: 'Target takes 20 Body damage every 3.999 seconds.',
  6928: 'Your speed is increased to 140% of normal.',
  6929: 'The target shapechanges.',
  6930: 'Your speed is increased to 150% of normal.',
  6936: 'Displays useful information about the target.',
  6937: 'Displays useful information about the target.',
  6938: 'Displays useful information about the target.',
  6939: 'Displays useful information about the target.',
  6941: 'The target shapechanges.',
  6942: 'The target shapechanges.',
  6943: 'The target shapechanges.',
  6947: "Creates an item in the caster's inventory.",
  6948: "Creates an item in the caster's inventory.",
  6949: "Creates an item in the caster's inventory.",
  6951: 'Your have a 35% increased chance to uncover hidden opponents. Your ability to stealth is also increased, if you possess it.',
  6952: 'Your have a 35% increased chance to uncover hidden opponents. Your ability to stealth is also increased, if you possess it.',
  6953: 'The target regenerates 60 health every 4.999 sec.',
  6954: "Decreases the target's resistances to Thrust damage by 15%.",
  6957: 'Absorbs 75% style damage.',
  6958: 'Absorbs 50% style damage.',
  6960: 'Target does 8 times more damage to siege weapons and doors.',
  6961: 'Heals target within view of the caster for 33% health.',
  6962: 'Brings the target back to life, restores 10% and 0% power and endurance and suffers no experience or constitution loss.',
  6964: 'Target gains a temporary health buffer that absorbs 20% of the physical damage dealt, up to a maximum of 200 damage.',
  6965: "Increases the target's resistance to Crush, Slash and Thrust damage by 10%.",
  6966: "Increases the target's resistance to Crush, Slash and Thrust damage by 10%.",
  6968: "The target's armor and health are improved by 5% while within range of this aura.",
  6969: 'Target recovers from the effects of resurrection.',
  6970: 'Decreases the stats of the target by 30 and adds them to the caster of this spell.',
  6971: 'Decreases the stats of the target by 25 and adds them to the caster of this spell.',
  6972: 'You gain a 4% bonus to armor and health.',
  6973: 'Heals cast on you are 10% more effective.',
  6974: 'Heals cast on you are 10% more effective.',
  6976: 'The target shapechanges.',
  6978: 'Target takes 25 Body damage every 5.999 seconds.',
  6979: "The target's spell range and spell penetration are improved by 5% while within range of this aura.",
  6980: 'If low on health, the target will convert 25% of their available power into health.',
  6981: "Increases the target's resistance to Crush, Slash and Thrust damage by 3%.",
  6982: "Target becomes disoriented for 1:00 min. Reduces target's melee to-hit chance by 10%. Reduces target's spell resist piercing by 10%.",
  6983: "Target becomes disoriented for 1:00 min. Reduces target's melee to-hit chance by 5%. Reduces target's spell resist piercing by 5%.",
  6984: "Target becomes 5% less effective at casting and resisting spells 5%. Reports target's primary specialization.",
  6985: '10% of all healing cast on the target restores endurance rather than health.',
  6987: 'Summons an elemental spirit to attack the target.',
  6988: 'Summons an elemental spirit to attack the target.',
  6989: 'Summons an elemental spirit to attack the target.',
  8702: 'Target takes 35 Body damage every 4.999 seconds.',
  8704: 'You regenerate 10% health, endurance and power every 4.999 sec.',
  8705: 'You regenerate 5% health, endurance and power every 4.999 sec.',
  8706: 'Damages and removes all illusions from the target.',
  8707: "Target's movement is reduced by 25% and their combat accuracy is reduced by 10% for 30 sec.This snare is not broken when the target is struck in battle.",
  8709: 'The target shapechanges.',
  8710: 'You become immune to the next stun spell cast on yourself.',
  8711: 'You become immune to the next mesmerize spell cast on yourself.',
  8712: 'Bedazzles target, causing it to suffer a 15% chance to miscast and a 15% chance to fumble for 30 sec.',
  8713: 'Bedazzles target, causing it to suffer a 10% chance to miscast and a 10% chance to fumble for 30 sec.',
  8714: 'You gain a 50% immunity to melee damage and a 50 bonus to all stats for 15 sec.',
  8716: '50% of damage done to you by the next spell is converted to healing.',
  8717: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (10%), power (10%) and endurance (10%).',
  8720: 'Target takes 30 Body damage every 4.999 seconds.',
  8722: 'Decreases the stats of the target by 40 and adds them to the caster of this spell.',
  8725: 'A magical bolt shoots toward the target, exploding on impact for 100.0 Energy damage. Can be blocked.',
  8728: 'The target shapechanges.',
  8730: 'The target shapechanges.',
  8733: 'Target takes 40 Body damage every 4.999 seconds.',
  8734: 'Triggers the following spell with a 5% chance when being attacked.',
  8735: 'Does 225.0 Spirit to the target. A portion of the damage is returned to the caster as health (7%), power (7%) and endurance (7%).',
  8736: 'The target regains 50% power points.',
  8737: 'Does 150.0 Spirit to the target. A portion of the damage is returned to the caster as health (7%), power (7%) and endurance (7%).',
  8738: 'Every stat of the target is decreased by 10% for 30 sec.',
  8739: 'You gain a 25% immunity to melee damage and a 25 bonus to all stats for 20 sec.',
  8740: 'Grants you a 10% chance to cheat death.',
  8741: "Your melee attacks have a 10% bonus to land for the spell's duration.",
  8742: "Reduces the target's absorption (ABS) by 10%.",
  8750: 'You take 75% less damage when falling.',
  8751: "The target's spell range and spell penetration are improved by 5% while within range of this aura.",
  8752: "Decreases the target's resistances to Crush, Slash and Thrust damage by 10%.",
  8753: "Target's all stats are reduced by 25.",
  8755: 'Target takes 25 Body damage every 4.999 seconds.',
  8756: "Target becomes disoriented for 15 sec. Reduces target's melee to-hit chance by 20%. Reduces target's spell resist piercing by 0%.",
  8757: 'You take 75% less damage when falling.',
  8758: "Target becomes disoriented for 15 sec. Reduces target's melee to-hit chance by 20%. Reduces target's spell resist piercing by 0%.",
  8759: 'The target regains 25% hit points.',
  8760: 'The target regains 25% power points.',
  8762: "Reduces the target's armor factor (AF) by 50 for 1:00 min.",
  8763: 'Target takes 35 Body damage every 4.999 seconds.',
  8764: 'Triggers the following spell with a 5% chance on own attacks.',
  8766: 'Does 75.0 Heat damage to the target.',
  8767: "Target becomes disoriented for 1:00 min. Reduces target's melee to-hit chance by 10%. Reduces target's spell resist piercing by 10%.",
  8770: 'Channeling this item calls down the protection of the stars upon yourself and anyone near you.',
  8783: 'Your melee attacks do additional 4.8 Spirit damage.',
  8785: "Target becomes disoriented for 15 sec. Reduces target's melee to-hit chance by 5%. Reduces target's spell resist piercing by 10%.",
  8786: "Decreases the target's resistances to Slash damage by 5%.",
  8788: "Decreases the target's resistances to Thrust damage by 5%.",
  8789: "Your melee attacks have a 10% bonus to land for the spell's duration.",
  8798: 'The target deals 6.1 Spirit damage to enemies that hit them with a melee attack.',
  8799: 'The target deals 6.1 Matter damage to enemies that hit them with a melee attack.',
  9419: 'The target will be shape changed.  Duration 10:00 min',
  9433: 'The target deals 6.1 Spirit damage to enemies that hit them with a melee attack.',
  9442: 'Target recovers from the effects of resurrection.',
  9443: 'You become immune to the next mesmerize spell cast on yourself.',
  9600: "Reduces the target's armor factor (AF) by 60 for 30 sec.",
  9602: 'Summons an elemental spirit to attack the target.',
  9603: 'Does 100.0 Essence to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  9604: 'Spreadheal for 100.',
  9605: 'The target regains 200 hit points.',
  9606: "Target's attack speed reduced by 50%.",
  9608: '60% endurance is stolen from the target and given to the caster.',
  9609: 'A soothing wisp will be summoned to follow and heal the targeted player',
  9611: 'This ability removes shields and stat buffs off of enemy targets.',
  9614: "Increases the target's resistance to All Magic damage by 30%.",
  9615: 'Summons an elemental spirit to attack the target.',
  9616: 'Triggers the following spell with a 10% chance when being attacked.',
  9618: 'Does 95.0 Matter damage to the target.',
  9620: 'Absorbs 75% style damage.',
  9621: "Creates an item in the caster's inventory.",
  9622: "Creates an item in the caster's inventory.",
  9623: "Creates an item in the caster's inventory.",
  9624: "Creates an item in the caster's inventory.",
  9625: 'Does 95.0 Heat damage to the target.',
  9626: 'Does 95.0 Cold damage to the target.',
  9627: 'Does 95.0 Energy damage to the target.',
  9628: 'Target takes 10 Matter damage every 4.000 seconds.',
  9629: "Creates an item in the caster's inventory.",
  9630: "Creates an item in the caster's inventory.",
  9631: "Creates an item in the caster's inventory.",
  9635: 'The target deals 5.6 Heat damage to enemies that hit them with a melee attack.',
  9638: "The target's combat effectiveness is reduced by 25%.",
  9639: 'The target will be shape changed.  Duration 10:00 min',
  9653: 'Decreases the stats of the target by 60 and adds them to the caster of this spell.',
  9654: 'Summons an elemental spirit to attack the target.',
  9656: 'A magical bolt shoots toward the target, exploding on impact for 200.0 Essence damage. Can be blocked.',
  9658: 'Does 150.0 Essence damage to the target.',
  9661: "The fire this weapon can produce will have a mind of its own and will chase after its owner's enemies.",
  9662: 'You regenerate 82 health every 1.999 sec.',
  9664: '10% of any damage done to you by the next spell is converted to healing.',
  9671: "Creates an item in the caster's inventory.",
  9672: "When used during night time hours, an item is created in the caster's inventory.",
  9698: "Creates an item in the caster's inventory.",
  9711: "Creates an item in the caster's inventory.",
  9712: "Creates an item in the caster's inventory.",
  9713: "Creates an item in the caster's inventory.",
  9714: "Creates an item in the caster's inventory.",
  9715: "Decreases the target's resistances to Slash damage by 15%.",
  9719: 'The target is slowed by 15%. Does 65.0 Essence damage to the target.',
  9720: 'Inflicts a wasting disease on the target that slows target by 15%, reduces its strength by 55 and inhibits healing by 50%.',
  9722: 'Lightning Storm \n A bolt of lightning initially strikes the target, then a lightning storm forms. \n Lightning from the storm can strike the target multiple times until the storm dissipates.',
  9723: "Increase target's fumble chance by 50%.",
  9734: 'Summons an elemental spirit to attack the target.',
  9735: 'All mesmerization effects are removed from the target.',
  10150: 'The target is slowed by 40%.',
  10152: 'Triggers the following spell with a 10% chance when being attacked.',
  10155: 'The target regains 20% hit points.',
  10156: 'The target regains 20% hit points.',
  10157: 'The target regains 20% hit points.',
  10158: 'The target regains 20% power points.',
  10159: 'The target regains 20% power points.',
  10160: 'The target regains 20% power points.',
  10162: 'The target regains 20% power points.',
  10163: 'You regain -20 endurance.',
  10164: 'You regain -20 endurance.',
  10165: 'You regain -30 endurance.',
  10166: 'Increases your armor factor (AF) by 25.',
  10167: 'Increases your armor factor (AF) by 35.',
  10168: 'Increases your armor factor (AF) by 45.',
  10169: "Target's acuity are increased by 25.",
  10170: "Target's acuity are increased by 35.",
  10171: "Target's acuity are increased by 45.",
  10172: "Target's strength and constitution are increased by 25.",
  10173: "Target's strength and constitution are increased by 35.",
  10174: "Target's strength and constitution are increased by 45.",
  10175: "Target's dexterity and quickness are increased by 25.",
  10176: "Target's dexterity and quickness are increased by 35.",
  10177: "Target's dexterity and quickness are increased by 45.",
  10178: "Reduces the target's absorption (ABS) by 20%%.",
  10179: "Reduces the target's armor factor (AF) by 40 for 30 sec.",
  10180: "Target's attack speed reduced by 40%.",
  10181: "Target's strength and constitution are reduced by 40.",
  10182: "Target's dexterity and quickness are reduced by 40.",
  10183: 'The target loses 15 endurance.',
  10184: 'Transfers 75 power from the caster to the target.',
  10185: "Increases the target's strength by 50.",
  10186: "Target's dexterity and quickness are increased by 50.",
  10208: 'Activating the power of the belt will summon forth a variety of weapons for use in combat.',
  10323: 'Increases your Flexible by 10%.',
  10335: 'Increases your Critical by 10%.',
  10337: 'Increases your Scythe by 10%.',
  10340: '10% of any damage done to you by the next spell is converted to healing.',
  10341: 'Returns 10% damage.',
  10461: "Target's strength and constitution are increased by 75.",
  10463: 'Increases your armor factor (AF) by 75.',
  10464: "Target's dexterity and quickness are increased by 75.",
  10555: 'Summons an elemental spirit to attack the target.',
  10556: 'Summons an elemental spirit to attack the target.',
  10557: 'Summons an elemental spirit to attack the target.',
  10558: 'Summons an elemental spirit to attack the target.',
  10850: 'Increases your armor factor (AF) by 60.',
  10851: "Target's acuity are increased by 60.",
  10852: "Target's strength and constitution are increased by 60.",
  10853: "Target's dexterity and quickness are increased by 60.",
  10855: 'The target takes 19.5 Body damage and the attacker is healed for 100% of the damage dealt.',
  10857: 'The target takes 32.5 Body damage and the attacker is healed for 100% of the damage dealt.',
  10858: 'The target takes 39.0 Body damage and the attacker is healed for 100% of the damage dealt.',
  10860: 'The target takes 52.0 Body damage and the attacker is healed for 100% of the damage dealt.',
  10861: 'The target takes 58.5 Body damage and the attacker is healed for 100% of the damage dealt.',
  10866: 'The target takes 39.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10867: 'The target takes 45.5 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10868: 'The target takes 52.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10869: 'The target takes 58.5 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10872: 'The target takes 26.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10873: 'The target takes 32.5 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10874: 'The target takes 39.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10875: 'The target takes 45.5 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10876: 'The target takes 52.0 Cold damage and the attacker is healed for 100% of the damage dealt.',
  10879: 'Target takes 16 Matter damage every 4.000 seconds.',
  10881: 'Target takes 30 Matter damage every 4.000 seconds.',
  10884: 'Target takes 50 Matter damage every 4.000 seconds.',
  10885: 'Target takes 57 Matter damage every 4.000 seconds.',
  10890: 'Target takes 37 Body damage every 4.000 seconds.',
  10891: 'Target takes 43 Body damage every 4.000 seconds.',
  10893: 'Target takes 57 Body damage every 4.000 seconds.',
  10895: 'Target takes 16 Energy damage every 4.000 seconds.',
  10896: 'Target takes 23 Energy damage every 4.000 seconds.',
  10897: 'Target takes 30 Energy damage every 4.000 seconds.',
  10899: 'Target takes 43 Energy damage every 4.000 seconds.',
  10900: 'Target takes 50 Energy damage every 4.000 seconds.',
  10901: 'Target takes 57 Energy damage every 4.000 seconds.',
  10902: 'Target takes 9 Heat damage every 4.999 seconds.',
  10904: 'Target takes 23 Heat damage every 4.999 seconds.',
  10905: 'Target takes 30 Heat damage every 4.999 seconds.',
  10907: 'You regenerate 10 extra health.',
  10908: 'You regenerate 20 extra health.',
  10910: "Target's strength and constitution are reduced by 12.",
  10911: "Target's strength and constitution are reduced by 23.",
  10912: "Target's strength and constitution are reduced by 34.",
  10913: "Target's strength and constitution are reduced by 45.",
  10916: "Target's strength and constitution are reduced by 34.",
  10917: "Target's strength and constitution are reduced by 45.",
  10920: "Target's strength and constitution are reduced by 34.",
  10921: "Target's strength and constitution are reduced by 45.",
  10922: "Target's dexterity and quickness are reduced by 12.",
  10924: "Target's dexterity and quickness are reduced by 34.",
  10925: "Target's dexterity and quickness are reduced by 45.",
  10929: "Target's dexterity and quickness are reduced by 45.",
  10930: "Target's dexterity and quickness are reduced by 12.",
  10932: "Target's dexterity and quickness are reduced by 34.",
  10933: "Target's dexterity and quickness are reduced by 45.",
  10936: 'Increases your combat speed by 15%.',
  10937: 'Increases your combat speed by 17%.',
  10940: 'Increases your combat speed by 15%.',
  10941: 'Increases your combat speed by 17%.',
  11070: "Clears the monster's mind, causing it to forget who it was attacking. Negates any spells currently being cast by enemy player targets, but does not interrupt them unless resisted.",
  11071: 'The pet casts the following spell.',
  11072: 'The pet casts the following spell.',
  11073: 'The pet casts the following spell.',
  11077: 'Triggers the following spell with a 15% chance when being attacked.',
  11079: "Decreases the target's resistances to Slash damage by 20%.",
  11081: 'You regenerate 5% health, endurance and power every 4.999 sec.',
  11082: 'You regain 75 endurance.',
  11083: "Increases the target's resistance to Crush, Slash and Thrust damage by 5%.",
  11085: '10% Accuracy bonus granted to the group for landing all spells, melee and ranged attacks.  Duration: 5 minutes',
  11087: 'The target is slowed by 30%.',
  11088: 'Does 75.0 Cold damage to the target.',
  11089: 'Does 75.0 Energy damage to the target.',
  11091: "Decreases the target's resistances to Thrust damage by 20%.",
  11092: 'The target regains 50% power points.',
  11093: 'Grants you 10% chance to penetrate magical resistances.',
  11094: 'You gain a 10% bonus to armor and health.',
  11095: "Decreases the target's resistances to Crush damage by 20%.",
  11210: 'Damages and removes all illusions from the target.',
  11242: 'The pet casts the following spell.',
  11257: 'The pet casts the following spell.',
  11298: 'The pet casts the following spell.',
  11299: 'The pet casts the following spell.',
  11670: 'Increases your constitution by 14.',
  11790: '10% endurance is stolen from the target and given to the caster.',
  11831: "Increase target's fumble chance by 10%.",
  11955: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  11966: 'Does 20.0 Matter damage to the target.',
  11967: 'Does 30.0 Matter damage to the target.',
  11968: 'Does 40.0 Matter damage to the target.',
  11969: 'Does 50.0 Matter damage to the target.',
  11970: 'Does 20.0 Energy damage to the target.',
  11971: 'Does 30.0 Energy damage to the target.',
  11972: 'Does 40.0 Energy damage to the target.',
  11973: 'Does 50.0 Energy damage to the target.',
  11985: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  11986: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  11987: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  11989: 'Does 331.5 Energy damage to the target.',
  12050: 'Target does 20 times more damage to siege weapons and doors.',
  12051: 'Does 1000.0 Essence damage to the target.',
  12200: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  12201: 'Increases your combat speed by 20%.',
  12202: 'Increases your armor factor (AF) by 75.',
  12203: "Target's strength and constitution are increased by 75.",
  12204: "Target's dexterity and quickness are increased by 75.",
  12205: 'The target deals 5.1 Heat damage to enemies that hit them with a melee attack.',
  12206: 'The target regains 230 hit points.',
  12207: 'The target regains 80 hit points.',
  12208: 'Does 95.0 Heat damage to the target.',
  12209: 'Increases your combat speed by 20%.',
  12210: "Target's acuity are increased by 75.",
  12211: 'The target regains 230 hit points.',
  12212: 'You regenerate 4 extra power.',
  12213: 'You regenerate 52 extra health.',
  12214: 'Your melee attacks do additional 11.3 Matter damage.',
  12224: 'Does 95.0 Heat damage to the target.',
  12225: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  12226: 'Target takes 64 Matter damage every 4.000 seconds.',
  12227: 'The target is stunned and cannot take any actions.',
  12228: 'The target is stunned and cannot take any actions.',
  12229: 'The target is stunned and cannot take any actions.',
  12230: 'Target gains a temporary health buffer that absorbs 50% of the physical damage dealt, up to a maximum of 200 damage.',
  12900: 'You regenerate 5% health, endurance and power every 4.999 sec.',
  12901: "Increases the target's resistance to Crush, Slash and Thrust damage by 10%.",
  12902: 'The target regains 50% power points.',
  12903: "Increases the target's resistance to All Magic damage by 10%.",
  12904: 'Does 75.0 Heat damage to the target.',
  12905: 'Does 75.0 Cold damage to the target.',
  12906: 'Does 75.0 Spirit damage to the target.',
  12907: 'Increases your attack speed by 25%.',
  12908: 'Increases your attack speed by 25%.',
  12909: 'Increases your attack speed by 25%.',
  12910: 'Heals the target for 10% health, power and fatigue.',
  12911: 'Target gains a temporary health buffer that absorbs 50% of the magical damage dealt, up to a maximum of 200 damage.',
  12912: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12913: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12914: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12915: "Reduces the target's absorption (ABS) by 20%%.",
  12916: "Reduces the target's armor factor (AF) by 40 for 30 sec.",
  12917: "Reduces the target's absorption (ABS) by 20%%.",
  12918: "Reduces the target's armor factor (AF) by 40 for 30 sec.",
  12919: "Reduces the target's absorption (ABS) by 20%%.",
  12920: "Reduces the target's armor factor (AF) by 40 for 30 sec.",
  12921: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12922: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12923: 'Does 100.0 Body to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  12924: "Decreases the target's resistances to Slash damage by 20%.",
  12925: "Decreases the target's resistances to Thrust damage by 20%.",
  12926: "Decreases the target's resistances to Crush damage by 20%.",
  12927: "Decreases the target's resistances to Slash damage by 20%.",
  12928: "Decreases the target's resistances to Thrust damage by 20%.",
  12929: "Decreases the target's resistances to Crush damage by 20%.",
  12930: "Decreases the target's resistances to Slash damage by 20%.",
  12931: "Decreases the target's resistances to Thrust damage by 20%.",
  12932: "Decreases the target's resistances to Crush damage by 20%.",
  12933: 'A magical attack which causes the enemy to fumble their attacks while increasing your chance to hit.',
  12934: 'A magical attack which causes the enemy to fumble their attacks while increasing your chance to hit.',
  12935: 'A magical attack which causes the enemy to fumble their attacks while increasing your chance to hit.',
  12936: 'The target loses 25 endurance.',
  12937: 'The target loses 25 endurance.',
  12938: 'The target loses 25 endurance.',
  12939: "Target's attack speed reduced by 31%.",
  12941: "Target's attack speed reduced by 31%.",
  12996: 'Does 95.0 Spirit damage to the target.',
  13600: 'The target shapechanges.',
  13601: 'The target shapechanges.',
  13602: 'The target shapechanges.',
  13604: 'The target shapechanges.',
  13605: 'The target shapechanges.',
  13606: 'The target shapechanges.',
  13631: 'Increase RP and BP that is awarded by 10.0%.',
  13779: 'Returns 10% damage.',
  13780: "Withers a piece of the target's armor, reducing its effectiveness.",
  13784: 'Target takes 50 Essence damage every 4.000 seconds.',
  13793: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 200 damage.',
  13794: 'Heals the target for 10% health, power and fatigue.',
  13795: 'Does 100.0 Essence to the target. A portion of the damage is returned to the caster as health (20%), power (20%) and endurance (20%).',
  13796: 'Does 150.0 Essence damage to the target.',
  13797: 'The target regains 50% power points.',
  13799: 'You regenerate 5% health, endurance and power every 4.999 sec.',
  14512: 'You can breathe underwater and move at 100% of normal land speed.',
  14615: 'All nearsight effects are removed from the target.',
  14871: "Reduces the target's armor factor (AF) by 100 for 30 sec.",
  14903: 'The target regains 180 hit points.',
  14985: 'Summons an elemental spirit to attack the target.',
  14986: 'Summons an elemental spirit to attack the target.',
  14987: 'Target gains a temporary health buffer that absorbs 50% of the physical and magical damage dealt, up to a maximum of 350 damage.',
  16657: 'Does 44.2 Heat damage to the target.',
  16684: 'Increase RP and BP that is awarded by 10.0%.',
  16741: 'The target is slowed by 40%.',
  16742: 'Inflicts a wasting disease on the target that slows target by 15%, reduces its strength by 15 and inhibits healing by 50%.',
  16743: 'The target takes 70.5 Body damage and the attacker is healed for 70% of the damage dealt.',
  16744: 'Target takes 125 Heat damage every 2.999 seconds.',
  16745: 'The target is slowed by 40%.',
  16790: 'Does 20.0 Heat damage to the target.',
  16791: 'Does 30.0 Heat damage to the target.',
  16792: 'Does 40.0 Heat damage to the target.',
  16793: 'Does 50.0 Heat damage to the target.',
  16794: 'The target loses 30 endurance.',
  16795: 'Does 20.0 Cold damage to the target.',
  16796: 'Does 30.0 Cold damage to the target.',
  16797: 'Does 40.0 Cold damage to the target.',
  16798: 'Does 50.0 Cold damage to the target.',
  16850: 'Does 95.0 Spirit damage to the target.',
  16907: 'Your spell range and spell penetration are improved by 5% while within range of this aura.',
}
